// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login Account",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Input Email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Input Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.Response"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Registrasi Account",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Input Email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Input Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.Response"
                        }
                    }
                }
            }
        },
        "/movies": {
            "get": {
                "description": "Get All Movie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Movies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search Movie",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Movie",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit Movie",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort Movie",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.GetAllMovie"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Add Movies",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Id Movie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Edit tittle",
                        "name": "tittle",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update genre",
                        "name": "genre",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Update Image",
                        "name": "Image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Synopsis",
                        "name": "synopsis",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Author",
                        "name": "author",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Actors",
                        "name": "actors",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Realease Date",
                        "name": "release_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Duration",
                        "name": "duration",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Tag",
                        "name": "tag",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "$ref": "#/definitions/models.MoviesbyTag"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/movies/{id}": {
            "get": {
                "description": "Detail Movies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Detail Movie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "$ref": "#/definitions/models.MoviesNoTag"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Movies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Delete Movie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "$ref": "#/definitions/models.MoviesbyTag"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "patch": {
                "description": "Edit Movies",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Id Movie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Edit tittle",
                        "name": "tittle",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update genre",
                        "name": "genre",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Update Image",
                        "name": "Image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Synopsis",
                        "name": "synopsis",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Author",
                        "name": "author",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Actors",
                        "name": "actors",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Realease Date",
                        "name": "release_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Duration",
                        "name": "duration",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Tag",
                        "name": "tag",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "$ref": "#/definitions/models.Movie_body"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/orders": {
            "post": {
                "description": "Add Order tikers",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order Tiket"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "name": "cinema_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "cinema_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "genre",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "location",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "movie_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "payment_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "profile_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "quantity",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "seat_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "time",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "total_price",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "$ref": "#/definitions/models.OrderBody"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/orders/cinema/{id}": {
            "post": {
                "description": "Add Choose Cinema tikers",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order Tiket"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Select Movie Tiket",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search Name Cinema",
                        "name": "searchName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search Date Cinema",
                        "name": "searchDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search Time Cinema",
                        "name": "searchTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search Location Cinema",
                        "name": "searchLocation",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "$ref": "#/definitions/models.MoviesCinema"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get Profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "$ref": "#/definitions/models.PointProfile"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "patch": {
                "description": "Update Movies",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update First Name",
                        "name": "First_Name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Last Name",
                        "name": "Last_Name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Update Image",
                        "name": "Image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Update Phone_Number",
                        "name": "Phone_Number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Email",
                        "name": "Email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Update Password",
                        "name": "Password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "$ref": "#/definitions/models.Profile"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "page_info": {},
                "results": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.GetAllMovie": {
            "type": "object",
            "properties": {
                "genre": {
                    "type": "string",
                    "example": "Action"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string",
                    "example": "Spiderman.jpg"
                },
                "tittle": {
                    "type": "string",
                    "example": "Spiderman"
                }
            }
        },
        "models.Movie_body": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "genre": {
                    "type": "string",
                    "example": "Action"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string",
                    "example": "Spiderman.jpg"
                },
                "release_date": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string",
                    "example": "film action universal"
                },
                "tag": {
                    "description": "Release_date time.Time ` + "`" + `json:\"release_date\" form:\"release_date\"` + "`" + `\nDuration     time.Time ` + "`" + `json:\"duration\" form:\"duration\"` + "`" + `",
                    "type": "string"
                },
                "tittle": {
                    "type": "string",
                    "example": "Spiderman"
                }
            }
        },
        "models.MoviesCinema": {
            "type": "object",
            "properties": {
                "cinema": {
                    "type": "string"
                },
                "cinema_date": {
                    "type": "string"
                },
                "cinema_location": {
                    "type": "string"
                },
                "cinema_time": {
                    "type": "string"
                },
                "genre": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "tittle": {
                    "type": "string"
                }
            }
        },
        "models.MoviesNoTag": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "genre": {
                    "type": "string",
                    "example": "Action"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string",
                    "example": "Spiderman.jpg"
                },
                "release_date": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string",
                    "example": "film action universal"
                },
                "tittle": {
                    "type": "string",
                    "example": "Spiderman"
                }
            }
        },
        "models.MoviesbyTag": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "genre": {
                    "type": "string",
                    "example": "Action"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string",
                    "example": "Spiderman.jpg"
                },
                "synopsis": {
                    "type": "string",
                    "example": "film action universal"
                },
                "tag": {
                    "description": "Release_date time.Time ` + "`" + `json:\"release_date\" form:\"release_date\"` + "`" + `\nDuration     time.Time ` + "`" + `json:\"duration\" form:\"duration\"` + "`" + `",
                    "type": "string"
                },
                "tittle": {
                    "type": "string",
                    "example": "Spiderman"
                }
            }
        },
        "models.OrderBody": {
            "type": "object",
            "properties": {
                "cinema_id": {
                    "type": "integer"
                },
                "cinema_name": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "genre": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "movie_id": {
                    "type": "integer"
                },
                "payment_id": {
                    "type": "integer"
                },
                "profile_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "seat_id": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_price": {
                    "type": "integer"
                }
            }
        },
        "models.PointProfile": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "salah@mail.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Salah"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string",
                    "example": "salah.jpg"
                },
                "last_name": {
                    "type": "string",
                    "example": "Alaudin"
                },
                "password": {
                    "type": "string",
                    "example": "Salah1!"
                },
                "phone_number": {
                    "type": "string"
                },
                "point": {
                    "type": "integer"
                }
            }
        },
        "models.Profile": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "salah@mail.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Salah"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string",
                    "example": "salah.jpg"
                },
                "last_name": {
                    "type": "string",
                    "example": "Alaudin"
                },
                "password": {
                    "type": "string",
                    "example": "Salah1!"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "Profile server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
